name: Hello World

on:
  pull_request:
    branches: [ master ]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Hello...
        run: echo "Hello"
        
  world:
    container: node:slim
    steps:  
      - name: ...World
        run: echo "World"
