name: Pass the artifact (Manual)

on: 
  workflow_dispatch:
    inputs:
      name: 
        description: 'File to create'
        default: 'junk.txt'
        required: true

jobs:
  job_1:
    name: Create File
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        run: |
          echo "Hello World" > ${{ github.event.inputs.name }}
      - name: Upload the file
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: ${{ github.event.inputs.name }}

  job_2:
    name: Modify the file
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download the bundle
        uses: actions/download-artifact@v2
        with:
          name: bundle
      - name: Echo and modify
        run: |
          cat ${{ github.event.inputs.name }}
          echo "more" >> ${{ github.event.inputs.name }}
